### ISSUE TITLE
Can this code guess the total charge based on the provided bond level?

### ISSUE THREAD

**Issue by 9527567** [allison-group/indigo-bondorder#1]
We hope to guess the total charge through a complete bond order for more automated operations.

**Comment by janerallison** [comment]
No sorry, the code as it stands can't do that - it needs the total charge to get the bond orders and formal charges.
But the problem you're looking to solve sounds easier, as knowing the bond levels localises the electrons, and formal charge is easy to guess with bond orders, so total charge is even easier - you should just need a graph of the molecule, and then it’ll come out.
Please feel free to use our code (or its internal functions) to do this!

**Comment by 9527567** [comment]
Thank you very much for your suggestion. I will carefully study your code.
